package in.simplifymoney.ledgersync;

import static org.junit.jupiter.api.Assertions.assertEquals;

import in.simplifymoney.ledgersync.model.Category;
import in.simplifymoney.ledgersync.model.Direction;
import in.simplifymoney.ledgersync.model.NormalizedTxn;
import in.simplifymoney.ledgersync.store.Backfill;
import in.simplifymoney.ledgersync.store.DocumentStore;
import in.simplifymoney.ledgersync.store.SqlLedgerStore;
import java.math.BigDecimal;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.OffsetDateTime;
import java.time.YearMonth;
import java.util.ArrayList;
import java.util.EnumMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

class BackfillTest {

    @TempDir
    Path temporaryDirectory;

    @Test
    void canRunMoreThanOnceWithoutCreatingDuplicates()
            throws Exception {

        Path migrations =
                temporaryDirectory.resolve("migration");

        Files.createDirectories(migrations);

        Files.writeString(
                migrations.resolve("V1__initial.sql"),
                """
                CREATE TABLE ledger (
                    id BIGINT GENERATED BY DEFAULT
                        AS IDENTITY PRIMARY KEY,
                    account_last4 VARCHAR(4) NOT NULL,
                    occurred_at VARCHAR(40) NOT NULL,
                    direction VARCHAR(6) NOT NULL,
                    amount DECIMAL(14, 2) NOT NULL,
                    category VARCHAR(10) NOT NULL,
                    merchant VARCHAR(120),
                    source_message_ids VARCHAR(500) NOT NULL
                );
                """);

        Path database =
                temporaryDirectory.resolve("backfill-ledger");

        try (SqlLedgerStore source =
                     new SqlLedgerStore(database)) {

            source.migrate(migrations);

            source.save(transaction());

            FakeDocumentStore target =
                    new FakeDocumentStore();

            Backfill backfill =
                    new Backfill(source, target);

            assertEquals(
                    new Backfill.Result(1, 1, 0),
                    backfill.run());

            assertEquals(
                    new Backfill.Result(1, 0, 1),
                    backfill.run());

            assertEquals(1, target.transactions.size());
        }
    }

    private NormalizedTxn transaction() {
        return new NormalizedTxn(
                "4821",
                OffsetDateTime.parse(
                        "2026-07-04T20:24:00+05:30"),
                Direction.DEBIT,
                new BigDecimal("2499.50"),
                Category.SPEND,
                "AMAZON PAY",
                List.of("m-email", "m-sms"));
    }

    private static final class FakeDocumentStore
            implements DocumentStore {

        private final List<NormalizedTxn> transactions =
                new ArrayList<>();

        @Override
        public List<NormalizedTxn> forAccountMonth(
                String accountLast4,
                YearMonth month) {

            return transactions.stream()
                    .filter(transaction ->
                            transaction.accountLast4()
                                    .equals(accountLast4))
                    .filter(transaction ->
                            YearMonth.from(
                                            transaction.occurredAt())
                                    .equals(month))
                    .toList();
        }

        @Override
        public Map<Category, BigDecimal> categoryTotals(
                String accountLast4) {

            Map<Category, BigDecimal> totals =
                    new EnumMap<>(Category.class);

            for (Category category : Category.values()) {
                totals.put(
                        category,
                        BigDecimal.ZERO.setScale(2));
            }

            for (NormalizedTxn transaction : transactions) {
                if (transaction.accountLast4()
                        .equals(accountLast4)) {

                    totals.put(
                            transaction.category(),
                            totals.get(transaction.category())
                                    .add(transaction.amount()));
                }
            }

            return totals;
        }

        @Override
        public Optional<NormalizedTxn> byMessageId(
                String messageId) {

            return transactions.stream()
                    .filter(transaction ->
                            transaction.sourceMessageIds()
                                    .contains(messageId))
                    .findFirst();
        }

        @Override
        public void save(NormalizedTxn transaction) {
            boolean alreadyExists =
                    transaction.sourceMessageIds()
                            .stream()
                            .anyMatch(messageId ->
                                    byMessageId(messageId)
                                            .isPresent());

            if (!alreadyExists) {
                transactions.add(transaction);
            }
        }
    }
}