package in.simplifymoney.ledgersync;

import static org.junit.jupiter.api.Assertions.assertTrue;

import in.simplifymoney.ledgersync.model.Category;
import in.simplifymoney.ledgersync.model.Direction;
import in.simplifymoney.ledgersync.model.NormalizedTxn;
import in.simplifymoney.ledgersync.store.ConsistencyChecker;
import in.simplifymoney.ledgersync.store.DocumentStore;
import in.simplifymoney.ledgersync.store.SqlLedgerStore;
import java.math.BigDecimal;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.OffsetDateTime;
import java.time.YearMonth;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.EnumMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

class ConsistencyCheckerTest {

    @TempDir
    Path temporaryDirectory;

    @Test
    void namesTheTransactionAndTotalThatWereChanged()
            throws Exception {

        Path migrations =
                temporaryDirectory.resolve("migration");

        Files.createDirectories(migrations);

        Files.writeString(
                migrations.resolve("V1__initial.sql"),
                """
                CREATE TABLE ledger (
                    id BIGINT GENERATED BY DEFAULT
                        AS IDENTITY PRIMARY KEY,
                    account_last4 VARCHAR(4) NOT NULL,
                    occurred_at VARCHAR(40) NOT NULL,
                    direction VARCHAR(6) NOT NULL,
                    amount DECIMAL(14, 2) NOT NULL,
                    category VARCHAR(10) NOT NULL,
                    merchant VARCHAR(120),
                    source_message_ids VARCHAR(500) NOT NULL
                );
                """);

        Path database =
                temporaryDirectory.resolve("checker-ledger");

        try (SqlLedgerStore source =
                     new SqlLedgerStore(database)) {

            source.migrate(migrations);

            NormalizedTxn correct =
                    transaction(new BigDecimal("2499.50"));

            source.save(correct);

            FakeDocumentStore target =
                    new FakeDocumentStore();

            target.save(correct);

            ConsistencyChecker checker =
                    new ConsistencyChecker(source, target);

            assertTrue(checker.check().isEmpty());

            target.replace(
                    transaction(new BigDecimal("2500.50")));

            List<ConsistencyChecker.Divergence> differences =
                    checker.check();

            assertTrue(
                    differences.stream()
                            .anyMatch(difference ->
                                    difference.what().equals(
                                            "transaction for message m-sms")
                                            && difference.inSql()
                                            .contains("2499.50")
                                            && difference.inDocuments()
                                            .contains("2500.50")));

            assertTrue(
                    differences.stream()
                            .anyMatch(difference ->
                                    difference.what().equals(
                                            "category total 4821/SPEND")
                                            && difference.inSql()
                                            .equals("2499.50")
                                            && difference.inDocuments()
                                            .equals("2500.50")));
        }
    }

    private NormalizedTxn transaction(
            BigDecimal amount) {

        return new NormalizedTxn(
                "4821",
                OffsetDateTime.parse(
                        "2026-07-04T20:24:00+05:30"),
                Direction.DEBIT,
                amount,
                Category.SPEND,
                "AMAZON PAY",
                List.of("m-email", "m-sms"));
    }

    private static final class FakeDocumentStore
            implements DocumentStore {

        private final List<NormalizedTxn> transactions =
                new ArrayList<>();

        @Override
        public List<NormalizedTxn> forAccountMonth(
                String accountLast4,
                YearMonth month) {

            return transactions.stream()
                    .filter(transaction ->
                            transaction.accountLast4()
                                    .equals(accountLast4))
                    .filter(transaction ->
                            YearMonth.from(
                                            transaction.occurredAt())
                                    .equals(month))
                    .sorted(Comparator.comparing(
                                    NormalizedTxn::occurredAt)
                            .reversed())
                    .toList();
        }

        @Override
        public Map<Category, BigDecimal> categoryTotals(
                String accountLast4) {

            Map<Category, BigDecimal> totals =
                    new EnumMap<>(Category.class);

            for (Category category : Category.values()) {
                totals.put(
                        category,
                        BigDecimal.ZERO.setScale(2));
            }

            for (NormalizedTxn transaction : transactions) {
                if (transaction.accountLast4()
                        .equals(accountLast4)) {

                    totals.put(
                            transaction.category(),
                            totals.get(transaction.category())
                                    .add(transaction.amount()));
                }
            }

            return totals;
        }

        @Override
        public Optional<NormalizedTxn> byMessageId(
                String messageId) {

            return transactions.stream()
                    .filter(transaction ->
                            transaction.sourceMessageIds()
                                    .contains(messageId))
                    .findFirst();
        }

        @Override
        public void save(NormalizedTxn transaction) {
            transactions.add(transaction);
        }

        private void replace(NormalizedTxn transaction) {
            transactions.clear();
            transactions.add(transaction);
        }
    }
}