package in.simplifymoney.ledgersync;

import static org.junit.jupiter.api.Assertions.assertEquals;

import in.simplifymoney.ledgersync.model.Category;
import in.simplifymoney.ledgersync.model.Direction;
import in.simplifymoney.ledgersync.model.NormalizedTxn;
import in.simplifymoney.ledgersync.store.SqlLedgerStore;
import java.math.BigDecimal;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.OffsetDateTime;
import java.util.List;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

class SqlLedgerStoreTest {

    @TempDir
    Path temporaryDirectory;

    @Test
    void mergesDuplicateTransactionEvidence() throws Exception {
        Path migrationDirectory =
                temporaryDirectory.resolve("migration");

        Files.createDirectories(migrationDirectory);

        Files.writeString(
                migrationDirectory.resolve("V1__initial.sql"),
                """
                CREATE TABLE ledger (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    account_last4 VARCHAR(4) NOT NULL,
                    occurred_at VARCHAR(40) NOT NULL,
                    direction VARCHAR(6) NOT NULL,
                    amount DECIMAL(14, 2) NOT NULL,
                    category VARCHAR(10) NOT NULL,
                    merchant VARCHAR(120),
                    source_message_ids VARCHAR(500) NOT NULL
                );
                """);

        Path database =
                temporaryDirectory.resolve("test-ledger");

        try (SqlLedgerStore store =
                     new SqlLedgerStore(database)) {

            store.migrate(migrationDirectory);

            store.save(transaction("m-email"));
            store.save(transaction("m-sms"));

            assertEquals(1, store.count());
            assertEquals(1, store.all().size());

            assertEquals(
                    List.of("m-email", "m-sms"),
                    store.all().get(0).sourceMessageIds());
        }
    }

    private NormalizedTxn transaction(String messageId) {
        return new NormalizedTxn(
                "4821",
                OffsetDateTime.parse(
                        "2026-07-04T20:24:00+05:30"),
                Direction.DEBIT,
                new BigDecimal("2499.50"),
                Category.SPEND,
                "AMAZON PAY",
                List.of(messageId));
    }
}